export enum LexemeType {
    PLUS_OPERATOR, MINUS_OPERATOR,
    MUL_OPERATOR, DIVISION_OPERATOR,
    EQUAL_OPERATOR,
    POWER_OPERATOR,
    LEFT_BRACKET, RIGTH_BRACKET,
    REGULAR_STRING,
    COMA_SEPARATOR,
    FUNCTION,
    EOF
};